# Book settings
title: Models of the Mind
author: James Magnuson
logo: images/logo.png
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md"]
only_build_toc_files: true

bibtex_bibfiles:
  - about/citations.bib

latex:
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  navbar_number_sections : false
  announcement: "Announcements will appear here"
  # google_analytics_id: UA-11111111 # add your Google Analytics Tracking Code
  comments:
    hypothesis: false
    utterances:
      repo: "jsmagnuson/mdraft"
    dokieli: false
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

launch_buttons:
  notebook_interface : "jupyterlab"
  binderhub_url      : "https://mybinder.org"
  thebe              : true

repository:
  url          : https://github.com/jsmagnuson/mdraft
  path_to_book : ""
  branch       : main

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['files']
    bibtex_reference_style: author_year
    myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - substitution

    myst_substitutions:
      INSTRUCTOR: "James (Jim) Magnuson (he/his/him)"
      OFFICE: "Arjona 114"
      PHONE: "N/A"
      EMAIL: "james.magnuson@uconn.edu"
      COURSE_CODE: "PSYC 3884 [ugrad] and 5570-002 [grad]"
      CREDITS: "3 credits"
      TITLE: "Models of the Mind"
      PREREQS: "Instructor permission."
      TERM: "2023 Fall"
      ROOM: "Arjona 307"
      MEETING_TIMES: "Fridays, 9-12"
      ZOOM_LINK: "[Zoom](https://uconn-edu.zoom.us/j/95210029717?pwd=TWxsdjRrVnZmeDh1ak1XNzE5MTZKZz09)"
      COURSE_LINK: "https://firas.moosvi.com/courses/cosc123"
      FORMAT: "Lectures, Labs, Tutorials and they will all be running online in this course."
      TEXTBOOK: "We will not be needing a textbook for this course as you will be provided all the notes you need via the course website."

# Notes
# Template: https://firasm.github.io/jupyterbook_course_template
# Template repo: https://github.com/firasm/jupyterbook_course_template
#
